### PR TITLE
Update to handle Map data, restructure how data is stored

### PR DESCRIPTION
**Pull request by tri-hoang**
Map data type requires some pre-processing before it can be stored as JSON.
I also update to store the type so it can easily handle Map, as well as other data types when it need be.

### CODE REVIEW

**Comment by ryanjyost** [comment]
Sorry for the delay, I'll try to look at this tonight and merge if it makes sense.

I might end up providing prop functions to manipulate the data when saving to localStorage and when parsing from localStorage to react state, that way anyone can handle their data any way they want.

Thanks for helping out!

**Comment by ryanjyost** [comment]
Ok, I tested out your changes. You made an elegant way to handle the Map type, and it seems to work with everything, but I'm thinking it's too niche a problem to warrant including the <type> in the localStorage values by default. Trying to keep things simple for noobies.

In the spirit of keeping this component "simple" to start with, and allowing folks such as yourself to add/handle complexity as needed, I'm going to propose the following...

1. I'll create two new prop functions. `handleDataBeforeStorage` and `handleDataFromStorage` or something like that. These functions will take values being passed between web storage and react state, and let you return whatever new format you want.  You could plug your `encode_data` and `decode_data` in there, giving you and everyone greater flexibility to manipulate their data as they need.

2. I'll include your `encode_data` and `decode_data` as helper functions for everyone's benefit.

Let me know if you disagree - I can be persuaded and might be missing something with my solution!

**Comment by tri-hoang** [comment]
No worries at all @ryanjyost . I understand that everyone is busy with things.

And I actually did something similar to what you described, but as a plugin for Store.js (moreTypes: https://github.com/tri-hoang/Store.js-MoreTypes/blob/master/moretypes.js), a library that is used in this repo. This plugin is a drop in library to support both Map and Set. It also allows user to pass in their own encoding and decoding functions.

Just a quick note, I was using the same technique in this PR as I was building the plugin for Store.js. And during the development, I noticed that it wasn't able to work with Map nested within Map (I haven't check back with this repo if it's also the case here or not.) So I came up with another approach that solved the problem over at the plugin for Store.js. I can change it accordingly for this PR once we decided what to do. It's all in the source code above if you wanted to look at it.

So I think there are two ways to approach this:
1. Update react-simple-storage to use the moreTypes plugin. And also add `handleDataBeforeStorage` and `handleDataFromStorage` like you described, but just pass it to the plugin.

2. Implement `handleDataBeforeStorage` and `handleDataFromStorage` natively on this repo.

Please let me know what you think and I will update it accordingly.

**Comment by ryanjyost** [comment]
Wow @tri-hoang , glad someone who has thought a lot about this issue is helping me out! I've never even used the Map type...!

I love your first option, but I think the basic default, out-of-the-box component shouldn't have the object with `type` property and advanced handling. It feels like too much for beginners - b/c using `getItem` manually will result in an object, rather than the value they expect, and that might throw beginners off. 

Maybe the user opts-in with some `useAdvancedTypes` option? Or the component detects that a Map or Set is present, and uses your plugin?  Do you think that's doable?

So I propose we pursue your first suggestion, but only use the moreTypes plugin when the user decides to include it OR when a Map/Set is detected. I'd say the detection option is better - how bout you?

I'm all for that, and would greatly appreciate you're help if you're down!

**Comment by tri-hoang** [comment]
hey @ryanjyost , sorry for the late reply.
Your point is very reasonable and we definitely should make this easy to use for the general user.

I actually already implemented the detection with my plugin. It does everything behind the scene for Map/Set or any other custom defined types. It will detect and store Map/Set in a special container in storage. And it will automatically convert the special container to a Map/Set when retrieved. The plugin will not apply this behavior to any other regular data type.

There was an edge case of defining only the encoding and no decoding that causes some confusing behaviors. But I pushed a new version just now that should fixes it.

Please let me know if I am missing any point.
I will update this PR with what I have in mind, so it would be easier for you to test it out.

**Comment by ryanjyost** [comment]
Thanks @tri-hoang. When I have some free time I'll play around with your branch and merge if all seems solid.

**Comment by ryanjyost** [comment]
Ok @tri-hoang, I like your moreTypes plugin update, that works great.

I made some tweaks locally to your branch
-  use an ES6 "import" instead of "require" for store.js-moretypes
- remove the _decode and _encode function definitions
- remove the _decode and _encode in the hydrateStateWithStorage and saveStateToStorage methods

I think you can let me push changes following these instructions 
--> https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

OR you can make the tweaks on your end.

Almost ready to merge, thanks!

**Comment by tri-hoang** [comment]
hi @ryanjyost , I have followed the instructions and enabled it.
However, I have also made the proposed changes to this PR.

And I think our next step should be to implement a mechanism on `react-simple-storage` , for advanced users, to pass custom datatype handlers.
My plugin already has a mechanism to detect either encoder or decoder are provided and react accordingly. And this is an example of how to add custom data type (pulled from my plugin's documentation):
```
// Add handlers for the datatype
store.add_types({
    Person: {
        replacer: (obj) => ({first: obj.first, last: obj.last}),
        reviver: (val) => new Person(val)
    }
})
```
For each datatype, it needs the `datatype name` as `key`. And the `value` consists of an `encoder` with the name `replacer` and a `decoder` with the name `reviver`.

My proposal is to ask advanced users to define their handlers accordingly to above, and we can just pass it as is to the plugin as an arguement for `store.add_types()`.

Please let me know what you think and I can proceed accordingly.

**Comment by ryanjyost** [comment]
@tri-hoang, I published to npm with your changes, but deploying my example project with the updated react-simple-storage component failed, and after a few failed attempts to fix I removed the moreTypes plugin and republished to npm.

It seems that the plugin isn't being compiled to es5, and breaking the build/deploy process. I'm not sure how the Map type can be used if it's necessary to compile down to es5, given it's brand new in es6?

**Pull request merged**
